// Copyright 2026 A Few Good Coders (www.afewgoodcoders.com). All rights reserved.
// Use of this source code is governed by a BSD-style license.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "refresh_rate_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace refresh_rate {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// DisplayInfoMessage

DisplayInfoMessage::DisplayInfoMessage() {}

DisplayInfoMessage::DisplayInfoMessage(
  const double* current_rate,
  const double* max_rate,
  const double* min_rate,
  const EncodableList* supported_rates,
  const bool* is_variable_refresh_rate,
  const double* engine_target_rate,
  const bool* ios_pro_motion_enabled,
  const int64_t* android_api_level,
  const bool* is_low_power_mode,
  const int64_t* thermal_state_index,
  const bool* has_adaptive_refresh_rate,
  const std::string* display_server,
  const int64_t* monitor_count)
 : current_rate_(current_rate ? std::optional<double>(*current_rate) : std::nullopt),
    max_rate_(max_rate ? std::optional<double>(*max_rate) : std::nullopt),
    min_rate_(min_rate ? std::optional<double>(*min_rate) : std::nullopt),
    supported_rates_(supported_rates ? std::optional<EncodableList>(*supported_rates) : std::nullopt),
    is_variable_refresh_rate_(is_variable_refresh_rate ? std::optional<bool>(*is_variable_refresh_rate) : std::nullopt),
    engine_target_rate_(engine_target_rate ? std::optional<double>(*engine_target_rate) : std::nullopt),
    ios_pro_motion_enabled_(ios_pro_motion_enabled ? std::optional<bool>(*ios_pro_motion_enabled) : std::nullopt),
    android_api_level_(android_api_level ? std::optional<int64_t>(*android_api_level) : std::nullopt),
    is_low_power_mode_(is_low_power_mode ? std::optional<bool>(*is_low_power_mode) : std::nullopt),
    thermal_state_index_(thermal_state_index ? std::optional<int64_t>(*thermal_state_index) : std::nullopt),
    has_adaptive_refresh_rate_(has_adaptive_refresh_rate ? std::optional<bool>(*has_adaptive_refresh_rate) : std::nullopt),
    display_server_(display_server ? std::optional<std::string>(*display_server) : std::nullopt),
    monitor_count_(monitor_count ? std::optional<int64_t>(*monitor_count) : std::nullopt) {}

const double* DisplayInfoMessage::current_rate() const {
  return current_rate_ ? &(*current_rate_) : nullptr;
}

void DisplayInfoMessage::set_current_rate(const double* value_arg) {
  current_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_current_rate(double value_arg) {
  current_rate_ = value_arg;
}


const double* DisplayInfoMessage::max_rate() const {
  return max_rate_ ? &(*max_rate_) : nullptr;
}

void DisplayInfoMessage::set_max_rate(const double* value_arg) {
  max_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_max_rate(double value_arg) {
  max_rate_ = value_arg;
}


const double* DisplayInfoMessage::min_rate() const {
  return min_rate_ ? &(*min_rate_) : nullptr;
}

void DisplayInfoMessage::set_min_rate(const double* value_arg) {
  min_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_min_rate(double value_arg) {
  min_rate_ = value_arg;
}


const EncodableList* DisplayInfoMessage::supported_rates() const {
  return supported_rates_ ? &(*supported_rates_) : nullptr;
}

void DisplayInfoMessage::set_supported_rates(const EncodableList* value_arg) {
  supported_rates_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_supported_rates(const EncodableList& value_arg) {
  supported_rates_ = value_arg;
}


const bool* DisplayInfoMessage::is_variable_refresh_rate() const {
  return is_variable_refresh_rate_ ? &(*is_variable_refresh_rate_) : nullptr;
}

void DisplayInfoMessage::set_is_variable_refresh_rate(const bool* value_arg) {
  is_variable_refresh_rate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_is_variable_refresh_rate(bool value_arg) {
  is_variable_refresh_rate_ = value_arg;
}


const double* DisplayInfoMessage::engine_target_rate() const {
  return engine_target_rate_ ? &(*engine_target_rate_) : nullptr;
}

void DisplayInfoMessage::set_engine_target_rate(const double* value_arg) {
  engine_target_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_engine_target_rate(double value_arg) {
  engine_target_rate_ = value_arg;
}


const bool* DisplayInfoMessage::ios_pro_motion_enabled() const {
  return ios_pro_motion_enabled_ ? &(*ios_pro_motion_enabled_) : nullptr;
}

void DisplayInfoMessage::set_ios_pro_motion_enabled(const bool* value_arg) {
  ios_pro_motion_enabled_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_ios_pro_motion_enabled(bool value_arg) {
  ios_pro_motion_enabled_ = value_arg;
}


const int64_t* DisplayInfoMessage::android_api_level() const {
  return android_api_level_ ? &(*android_api_level_) : nullptr;
}

void DisplayInfoMessage::set_android_api_level(const int64_t* value_arg) {
  android_api_level_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_android_api_level(int64_t value_arg) {
  android_api_level_ = value_arg;
}


const bool* DisplayInfoMessage::is_low_power_mode() const {
  return is_low_power_mode_ ? &(*is_low_power_mode_) : nullptr;
}

void DisplayInfoMessage::set_is_low_power_mode(const bool* value_arg) {
  is_low_power_mode_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_is_low_power_mode(bool value_arg) {
  is_low_power_mode_ = value_arg;
}


const int64_t* DisplayInfoMessage::thermal_state_index() const {
  return thermal_state_index_ ? &(*thermal_state_index_) : nullptr;
}

void DisplayInfoMessage::set_thermal_state_index(const int64_t* value_arg) {
  thermal_state_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_thermal_state_index(int64_t value_arg) {
  thermal_state_index_ = value_arg;
}


const bool* DisplayInfoMessage::has_adaptive_refresh_rate() const {
  return has_adaptive_refresh_rate_ ? &(*has_adaptive_refresh_rate_) : nullptr;
}

void DisplayInfoMessage::set_has_adaptive_refresh_rate(const bool* value_arg) {
  has_adaptive_refresh_rate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_has_adaptive_refresh_rate(bool value_arg) {
  has_adaptive_refresh_rate_ = value_arg;
}


const std::string* DisplayInfoMessage::display_server() const {
  return display_server_ ? &(*display_server_) : nullptr;
}

void DisplayInfoMessage::set_display_server(const std::string_view* value_arg) {
  display_server_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_display_server(std::string_view value_arg) {
  display_server_ = value_arg;
}


const int64_t* DisplayInfoMessage::monitor_count() const {
  return monitor_count_ ? &(*monitor_count_) : nullptr;
}

void DisplayInfoMessage::set_monitor_count(const int64_t* value_arg) {
  monitor_count_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_monitor_count(int64_t value_arg) {
  monitor_count_ = value_arg;
}


EncodableList DisplayInfoMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(13);
  list.push_back(current_rate_ ? EncodableValue(*current_rate_) : EncodableValue());
  list.push_back(max_rate_ ? EncodableValue(*max_rate_) : EncodableValue());
  list.push_back(min_rate_ ? EncodableValue(*min_rate_) : EncodableValue());
  list.push_back(supported_rates_ ? EncodableValue(*supported_rates_) : EncodableValue());
  list.push_back(is_variable_refresh_rate_ ? EncodableValue(*is_variable_refresh_rate_) : EncodableValue());
  list.push_back(engine_target_rate_ ? EncodableValue(*engine_target_rate_) : EncodableValue());
  list.push_back(ios_pro_motion_enabled_ ? EncodableValue(*ios_pro_motion_enabled_) : EncodableValue());
  list.push_back(android_api_level_ ? EncodableValue(*android_api_level_) : EncodableValue());
  list.push_back(is_low_power_mode_ ? EncodableValue(*is_low_power_mode_) : EncodableValue());
  list.push_back(thermal_state_index_ ? EncodableValue(*thermal_state_index_) : EncodableValue());
  list.push_back(has_adaptive_refresh_rate_ ? EncodableValue(*has_adaptive_refresh_rate_) : EncodableValue());
  list.push_back(display_server_ ? EncodableValue(*display_server_) : EncodableValue());
  list.push_back(monitor_count_ ? EncodableValue(*monitor_count_) : EncodableValue());
  return list;
}

DisplayInfoMessage DisplayInfoMessage::FromEncodableList(const EncodableList& list) {
  DisplayInfoMessage decoded;
  auto& encodable_current_rate = list[0];
  if (!encodable_current_rate.IsNull()) {
    decoded.set_current_rate(std::get<double>(encodable_current_rate));
  }
  auto& encodable_max_rate = list[1];
  if (!encodable_max_rate.IsNull()) {
    decoded.set_max_rate(std::get<double>(encodable_max_rate));
  }
  auto& encodable_min_rate = list[2];
  if (!encodable_min_rate.IsNull()) {
    decoded.set_min_rate(std::get<double>(encodable_min_rate));
  }
  auto& encodable_supported_rates = list[3];
  if (!encodable_supported_rates.IsNull()) {
    decoded.set_supported_rates(std::get<EncodableList>(encodable_supported_rates));
  }
  auto& encodable_is_variable_refresh_rate = list[4];
  if (!encodable_is_variable_refresh_rate.IsNull()) {
    decoded.set_is_variable_refresh_rate(std::get<bool>(encodable_is_variable_refresh_rate));
  }
  auto& encodable_engine_target_rate = list[5];
  if (!encodable_engine_target_rate.IsNull()) {
    decoded.set_engine_target_rate(std::get<double>(encodable_engine_target_rate));
  }
  auto& encodable_ios_pro_motion_enabled = list[6];
  if (!encodable_ios_pro_motion_enabled.IsNull()) {
    decoded.set_ios_pro_motion_enabled(std::get<bool>(encodable_ios_pro_motion_enabled));
  }
  auto& encodable_android_api_level = list[7];
  if (!encodable_android_api_level.IsNull()) {
    decoded.set_android_api_level(std::get<int64_t>(encodable_android_api_level));
  }
  auto& encodable_is_low_power_mode = list[8];
  if (!encodable_is_low_power_mode.IsNull()) {
    decoded.set_is_low_power_mode(std::get<bool>(encodable_is_low_power_mode));
  }
  auto& encodable_thermal_state_index = list[9];
  if (!encodable_thermal_state_index.IsNull()) {
    decoded.set_thermal_state_index(std::get<int64_t>(encodable_thermal_state_index));
  }
  auto& encodable_has_adaptive_refresh_rate = list[10];
  if (!encodable_has_adaptive_refresh_rate.IsNull()) {
    decoded.set_has_adaptive_refresh_rate(std::get<bool>(encodable_has_adaptive_refresh_rate));
  }
  auto& encodable_display_server = list[11];
  if (!encodable_display_server.IsNull()) {
    decoded.set_display_server(std::get<std::string>(encodable_display_server));
  }
  auto& encodable_monitor_count = list[12];
  if (!encodable_monitor_count.IsNull()) {
    decoded.set_monitor_count(std::get<int64_t>(encodable_monitor_count));
  }
  return decoded;
}

// PreferenceMessage

PreferenceMessage::PreferenceMessage() {}

PreferenceMessage::PreferenceMessage(
  const NativePreferenceKind* kind,
  const double* fps,
  const int64_t* category,
  const NativeSwitchStrategy* strategy)
 : kind_(kind ? std::optional<NativePreferenceKind>(*kind) : std::nullopt),
    fps_(fps ? std::optional<double>(*fps) : std::nullopt),
    category_(category ? std::optional<int64_t>(*category) : std::nullopt),
    strategy_(strategy ? std::optional<NativeSwitchStrategy>(*strategy) : std::nullopt) {}

const NativePreferenceKind* PreferenceMessage::kind() const {
  return kind_ ? &(*kind_) : nullptr;
}

void PreferenceMessage::set_kind(const NativePreferenceKind* value_arg) {
  kind_ = value_arg ? std::optional<NativePreferenceKind>(*value_arg) : std::nullopt;
}

void PreferenceMessage::set_kind(const NativePreferenceKind& value_arg) {
  kind_ = value_arg;
}


const double* PreferenceMessage::fps() const {
  return fps_ ? &(*fps_) : nullptr;
}

void PreferenceMessage::set_fps(const double* value_arg) {
  fps_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void PreferenceMessage::set_fps(double value_arg) {
  fps_ = value_arg;
}


const int64_t* PreferenceMessage::category() const {
  return category_ ? &(*category_) : nullptr;
}

void PreferenceMessage::set_category(const int64_t* value_arg) {
  category_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PreferenceMessage::set_category(int64_t value_arg) {
  category_ = value_arg;
}


const NativeSwitchStrategy* PreferenceMessage::strategy() const {
  return strategy_ ? &(*strategy_) : nullptr;
}

void PreferenceMessage::set_strategy(const NativeSwitchStrategy* value_arg) {
  strategy_ = value_arg ? std::optional<NativeSwitchStrategy>(*value_arg) : std::nullopt;
}

void PreferenceMessage::set_strategy(const NativeSwitchStrategy& value_arg) {
  strategy_ = value_arg;
}


EncodableList PreferenceMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(kind_ ? CustomEncodableValue(*kind_) : EncodableValue());
  list.push_back(fps_ ? EncodableValue(*fps_) : EncodableValue());
  list.push_back(category_ ? EncodableValue(*category_) : EncodableValue());
  list.push_back(strategy_ ? CustomEncodableValue(*strategy_) : EncodableValue());
  return list;
}

PreferenceMessage PreferenceMessage::FromEncodableList(const EncodableList& list) {
  PreferenceMessage decoded;
  auto& encodable_kind = list[0];
  if (!encodable_kind.IsNull()) {
    decoded.set_kind(std::any_cast<const NativePreferenceKind&>(std::get<CustomEncodableValue>(encodable_kind)));
  }
  auto& encodable_fps = list[1];
  if (!encodable_fps.IsNull()) {
    decoded.set_fps(std::get<double>(encodable_fps));
  }
  auto& encodable_category = list[2];
  if (!encodable_category.IsNull()) {
    decoded.set_category(std::get<int64_t>(encodable_category));
  }
  auto& encodable_strategy = list[3];
  if (!encodable_strategy.IsNull()) {
    decoded.set_strategy(std::any_cast<const NativeSwitchStrategy&>(std::get<CustomEncodableValue>(encodable_strategy)));
  }
  return decoded;
}

// RequestResultMessage

RequestResultMessage::RequestResultMessage() {}

RequestResultMessage::RequestResultMessage(
  const NativeRequestStatus* status,
  const std::string* backend,
  const std::string* scope,
  const std::string* message,
  const PreferenceMessage* preference,
  const int64_t* observed_at_ms)
 : status_(status ? std::optional<NativeRequestStatus>(*status) : std::nullopt),
    backend_(backend ? std::optional<std::string>(*backend) : std::nullopt),
    scope_(scope ? std::optional<std::string>(*scope) : std::nullopt),
    message_(message ? std::optional<std::string>(*message) : std::nullopt),
    preference_(preference ? std::make_unique<PreferenceMessage>(*preference) : nullptr),
    observed_at_ms_(observed_at_ms ? std::optional<int64_t>(*observed_at_ms) : std::nullopt) {}

RequestResultMessage::RequestResultMessage(const RequestResultMessage& other)
 : status_(other.status_ ? std::optional<NativeRequestStatus>(*other.status_) : std::nullopt),
    backend_(other.backend_ ? std::optional<std::string>(*other.backend_) : std::nullopt),
    scope_(other.scope_ ? std::optional<std::string>(*other.scope_) : std::nullopt),
    message_(other.message_ ? std::optional<std::string>(*other.message_) : std::nullopt),
    preference_(other.preference_ ? std::make_unique<PreferenceMessage>(*other.preference_) : nullptr),
    observed_at_ms_(other.observed_at_ms_ ? std::optional<int64_t>(*other.observed_at_ms_) : std::nullopt) {}

RequestResultMessage& RequestResultMessage::operator=(const RequestResultMessage& other) {
  status_ = other.status_;
  backend_ = other.backend_;
  scope_ = other.scope_;
  message_ = other.message_;
  preference_ = other.preference_ ? std::make_unique<PreferenceMessage>(*other.preference_) : nullptr;
  observed_at_ms_ = other.observed_at_ms_;
  return *this;
}

const NativeRequestStatus* RequestResultMessage::status() const {
  return status_ ? &(*status_) : nullptr;
}

void RequestResultMessage::set_status(const NativeRequestStatus* value_arg) {
  status_ = value_arg ? std::optional<NativeRequestStatus>(*value_arg) : std::nullopt;
}

void RequestResultMessage::set_status(const NativeRequestStatus& value_arg) {
  status_ = value_arg;
}


const std::string* RequestResultMessage::backend() const {
  return backend_ ? &(*backend_) : nullptr;
}

void RequestResultMessage::set_backend(const std::string_view* value_arg) {
  backend_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void RequestResultMessage::set_backend(std::string_view value_arg) {
  backend_ = value_arg;
}


const std::string* RequestResultMessage::scope() const {
  return scope_ ? &(*scope_) : nullptr;
}

void RequestResultMessage::set_scope(const std::string_view* value_arg) {
  scope_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void RequestResultMessage::set_scope(std::string_view value_arg) {
  scope_ = value_arg;
}


const std::string* RequestResultMessage::message() const {
  return message_ ? &(*message_) : nullptr;
}

void RequestResultMessage::set_message(const std::string_view* value_arg) {
  message_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void RequestResultMessage::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


const PreferenceMessage* RequestResultMessage::preference() const {
  return preference_.get();
}

void RequestResultMessage::set_preference(const PreferenceMessage* value_arg) {
  preference_ = value_arg ? std::make_unique<PreferenceMessage>(*value_arg) : nullptr;
}

void RequestResultMessage::set_preference(const PreferenceMessage& value_arg) {
  preference_ = std::make_unique<PreferenceMessage>(value_arg);
}


const int64_t* RequestResultMessage::observed_at_ms() const {
  return observed_at_ms_ ? &(*observed_at_ms_) : nullptr;
}

void RequestResultMessage::set_observed_at_ms(const int64_t* value_arg) {
  observed_at_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void RequestResultMessage::set_observed_at_ms(int64_t value_arg) {
  observed_at_ms_ = value_arg;
}


EncodableList RequestResultMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(status_ ? CustomEncodableValue(*status_) : EncodableValue());
  list.push_back(backend_ ? EncodableValue(*backend_) : EncodableValue());
  list.push_back(scope_ ? EncodableValue(*scope_) : EncodableValue());
  list.push_back(message_ ? EncodableValue(*message_) : EncodableValue());
  list.push_back(preference_ ? CustomEncodableValue(*preference_) : EncodableValue());
  list.push_back(observed_at_ms_ ? EncodableValue(*observed_at_ms_) : EncodableValue());
  return list;
}

RequestResultMessage RequestResultMessage::FromEncodableList(const EncodableList& list) {
  RequestResultMessage decoded;
  auto& encodable_status = list[0];
  if (!encodable_status.IsNull()) {
    decoded.set_status(std::any_cast<const NativeRequestStatus&>(std::get<CustomEncodableValue>(encodable_status)));
  }
  auto& encodable_backend = list[1];
  if (!encodable_backend.IsNull()) {
    decoded.set_backend(std::get<std::string>(encodable_backend));
  }
  auto& encodable_scope = list[2];
  if (!encodable_scope.IsNull()) {
    decoded.set_scope(std::get<std::string>(encodable_scope));
  }
  auto& encodable_message = list[3];
  if (!encodable_message.IsNull()) {
    decoded.set_message(std::get<std::string>(encodable_message));
  }
  auto& encodable_preference = list[4];
  if (!encodable_preference.IsNull()) {
    decoded.set_preference(std::any_cast<const PreferenceMessage&>(std::get<CustomEncodableValue>(encodable_preference)));
  }
  auto& encodable_observed_at_ms = list[5];
  if (!encodable_observed_at_ms.IsNull()) {
    decoded.set_observed_at_ms(std::get<int64_t>(encodable_observed_at_ms));
  }
  return decoded;
}

// CapabilitiesMessage

CapabilitiesMessage::CapabilitiesMessage() {}

CapabilitiesMessage::CapabilitiesMessage(
  const bool* query,
  const bool* surface_voting,
  const bool* window_preferences,
  const bool* category_hints,
  const bool* engine_control,
  const bool* presentation_observation,
  const bool* at_least,
  const bool* content_matching,
  const bool* touch_boost,
  const bool* callback_observation)
 : query_(query ? std::optional<bool>(*query) : std::nullopt),
    surface_voting_(surface_voting ? std::optional<bool>(*surface_voting) : std::nullopt),
    window_preferences_(window_preferences ? std::optional<bool>(*window_preferences) : std::nullopt),
    category_hints_(category_hints ? std::optional<bool>(*category_hints) : std::nullopt),
    engine_control_(engine_control ? std::optional<bool>(*engine_control) : std::nullopt),
    presentation_observation_(presentation_observation ? std::optional<bool>(*presentation_observation) : std::nullopt),
    at_least_(at_least ? std::optional<bool>(*at_least) : std::nullopt),
    content_matching_(content_matching ? std::optional<bool>(*content_matching) : std::nullopt),
    touch_boost_(touch_boost ? std::optional<bool>(*touch_boost) : std::nullopt),
    callback_observation_(callback_observation ? std::optional<bool>(*callback_observation) : std::nullopt) {}

const bool* CapabilitiesMessage::query() const {
  return query_ ? &(*query_) : nullptr;
}

void CapabilitiesMessage::set_query(const bool* value_arg) {
  query_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_query(bool value_arg) {
  query_ = value_arg;
}


const bool* CapabilitiesMessage::surface_voting() const {
  return surface_voting_ ? &(*surface_voting_) : nullptr;
}

void CapabilitiesMessage::set_surface_voting(const bool* value_arg) {
  surface_voting_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_surface_voting(bool value_arg) {
  surface_voting_ = value_arg;
}


const bool* CapabilitiesMessage::window_preferences() const {
  return window_preferences_ ? &(*window_preferences_) : nullptr;
}

void CapabilitiesMessage::set_window_preferences(const bool* value_arg) {
  window_preferences_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_window_preferences(bool value_arg) {
  window_preferences_ = value_arg;
}


const bool* CapabilitiesMessage::category_hints() const {
  return category_hints_ ? &(*category_hints_) : nullptr;
}

void CapabilitiesMessage::set_category_hints(const bool* value_arg) {
  category_hints_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_category_hints(bool value_arg) {
  category_hints_ = value_arg;
}


const bool* CapabilitiesMessage::engine_control() const {
  return engine_control_ ? &(*engine_control_) : nullptr;
}

void CapabilitiesMessage::set_engine_control(const bool* value_arg) {
  engine_control_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_engine_control(bool value_arg) {
  engine_control_ = value_arg;
}


const bool* CapabilitiesMessage::presentation_observation() const {
  return presentation_observation_ ? &(*presentation_observation_) : nullptr;
}

void CapabilitiesMessage::set_presentation_observation(const bool* value_arg) {
  presentation_observation_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_presentation_observation(bool value_arg) {
  presentation_observation_ = value_arg;
}


const bool* CapabilitiesMessage::at_least() const {
  return at_least_ ? &(*at_least_) : nullptr;
}

void CapabilitiesMessage::set_at_least(const bool* value_arg) {
  at_least_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_at_least(bool value_arg) {
  at_least_ = value_arg;
}


const bool* CapabilitiesMessage::content_matching() const {
  return content_matching_ ? &(*content_matching_) : nullptr;
}

void CapabilitiesMessage::set_content_matching(const bool* value_arg) {
  content_matching_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_content_matching(bool value_arg) {
  content_matching_ = value_arg;
}


const bool* CapabilitiesMessage::touch_boost() const {
  return touch_boost_ ? &(*touch_boost_) : nullptr;
}

void CapabilitiesMessage::set_touch_boost(const bool* value_arg) {
  touch_boost_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_touch_boost(bool value_arg) {
  touch_boost_ = value_arg;
}


const bool* CapabilitiesMessage::callback_observation() const {
  return callback_observation_ ? &(*callback_observation_) : nullptr;
}

void CapabilitiesMessage::set_callback_observation(const bool* value_arg) {
  callback_observation_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CapabilitiesMessage::set_callback_observation(bool value_arg) {
  callback_observation_ = value_arg;
}


EncodableList CapabilitiesMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(10);
  list.push_back(query_ ? EncodableValue(*query_) : EncodableValue());
  list.push_back(surface_voting_ ? EncodableValue(*surface_voting_) : EncodableValue());
  list.push_back(window_preferences_ ? EncodableValue(*window_preferences_) : EncodableValue());
  list.push_back(category_hints_ ? EncodableValue(*category_hints_) : EncodableValue());
  list.push_back(engine_control_ ? EncodableValue(*engine_control_) : EncodableValue());
  list.push_back(presentation_observation_ ? EncodableValue(*presentation_observation_) : EncodableValue());
  list.push_back(at_least_ ? EncodableValue(*at_least_) : EncodableValue());
  list.push_back(content_matching_ ? EncodableValue(*content_matching_) : EncodableValue());
  list.push_back(touch_boost_ ? EncodableValue(*touch_boost_) : EncodableValue());
  list.push_back(callback_observation_ ? EncodableValue(*callback_observation_) : EncodableValue());
  return list;
}

CapabilitiesMessage CapabilitiesMessage::FromEncodableList(const EncodableList& list) {
  CapabilitiesMessage decoded;
  auto& encodable_query = list[0];
  if (!encodable_query.IsNull()) {
    decoded.set_query(std::get<bool>(encodable_query));
  }
  auto& encodable_surface_voting = list[1];
  if (!encodable_surface_voting.IsNull()) {
    decoded.set_surface_voting(std::get<bool>(encodable_surface_voting));
  }
  auto& encodable_window_preferences = list[2];
  if (!encodable_window_preferences.IsNull()) {
    decoded.set_window_preferences(std::get<bool>(encodable_window_preferences));
  }
  auto& encodable_category_hints = list[3];
  if (!encodable_category_hints.IsNull()) {
    decoded.set_category_hints(std::get<bool>(encodable_category_hints));
  }
  auto& encodable_engine_control = list[4];
  if (!encodable_engine_control.IsNull()) {
    decoded.set_engine_control(std::get<bool>(encodable_engine_control));
  }
  auto& encodable_presentation_observation = list[5];
  if (!encodable_presentation_observation.IsNull()) {
    decoded.set_presentation_observation(std::get<bool>(encodable_presentation_observation));
  }
  auto& encodable_at_least = list[6];
  if (!encodable_at_least.IsNull()) {
    decoded.set_at_least(std::get<bool>(encodable_at_least));
  }
  auto& encodable_content_matching = list[7];
  if (!encodable_content_matching.IsNull()) {
    decoded.set_content_matching(std::get<bool>(encodable_content_matching));
  }
  auto& encodable_touch_boost = list[8];
  if (!encodable_touch_boost.IsNull()) {
    decoded.set_touch_boost(std::get<bool>(encodable_touch_boost));
  }
  auto& encodable_callback_observation = list[9];
  if (!encodable_callback_observation.IsNull()) {
    decoded.set_callback_observation(std::get<bool>(encodable_callback_observation));
  }
  return decoded;
}

// DiagnosticsMessage

DiagnosticsMessage::DiagnosticsMessage() {}

DiagnosticsMessage::DiagnosticsMessage(
  const std::string* source,
  const std::string* display_id,
  const std::string* scope,
  const double* current_hz,
  const double* maximum_hz,
  const double* suggested_normal_hz,
  const double* suggested_high_hz,
  const double* callback_hz,
  const double* expected_callback_hz,
  const int64_t* sample_count,
  const int64_t* window_us,
  const bool* activity_attached,
  const bool* surface_available,
  const bool* touch_boost_enabled,
  const RequestResultMessage* last_native_request,
  const int64_t* target_generation,
  const int64_t* submission_count)
 : source_(source ? std::optional<std::string>(*source) : std::nullopt),
    display_id_(display_id ? std::optional<std::string>(*display_id) : std::nullopt),
    scope_(scope ? std::optional<std::string>(*scope) : std::nullopt),
    current_hz_(current_hz ? std::optional<double>(*current_hz) : std::nullopt),
    maximum_hz_(maximum_hz ? std::optional<double>(*maximum_hz) : std::nullopt),
    suggested_normal_hz_(suggested_normal_hz ? std::optional<double>(*suggested_normal_hz) : std::nullopt),
    suggested_high_hz_(suggested_high_hz ? std::optional<double>(*suggested_high_hz) : std::nullopt),
    callback_hz_(callback_hz ? std::optional<double>(*callback_hz) : std::nullopt),
    expected_callback_hz_(expected_callback_hz ? std::optional<double>(*expected_callback_hz) : std::nullopt),
    sample_count_(sample_count ? std::optional<int64_t>(*sample_count) : std::nullopt),
    window_us_(window_us ? std::optional<int64_t>(*window_us) : std::nullopt),
    activity_attached_(activity_attached ? std::optional<bool>(*activity_attached) : std::nullopt),
    surface_available_(surface_available ? std::optional<bool>(*surface_available) : std::nullopt),
    touch_boost_enabled_(touch_boost_enabled ? std::optional<bool>(*touch_boost_enabled) : std::nullopt),
    last_native_request_(last_native_request ? std::make_unique<RequestResultMessage>(*last_native_request) : nullptr),
    target_generation_(target_generation ? std::optional<int64_t>(*target_generation) : std::nullopt),
    submission_count_(submission_count ? std::optional<int64_t>(*submission_count) : std::nullopt) {}

DiagnosticsMessage::DiagnosticsMessage(const DiagnosticsMessage& other)
 : source_(other.source_ ? std::optional<std::string>(*other.source_) : std::nullopt),
    display_id_(other.display_id_ ? std::optional<std::string>(*other.display_id_) : std::nullopt),
    scope_(other.scope_ ? std::optional<std::string>(*other.scope_) : std::nullopt),
    current_hz_(other.current_hz_ ? std::optional<double>(*other.current_hz_) : std::nullopt),
    maximum_hz_(other.maximum_hz_ ? std::optional<double>(*other.maximum_hz_) : std::nullopt),
    suggested_normal_hz_(other.suggested_normal_hz_ ? std::optional<double>(*other.suggested_normal_hz_) : std::nullopt),
    suggested_high_hz_(other.suggested_high_hz_ ? std::optional<double>(*other.suggested_high_hz_) : std::nullopt),
    callback_hz_(other.callback_hz_ ? std::optional<double>(*other.callback_hz_) : std::nullopt),
    expected_callback_hz_(other.expected_callback_hz_ ? std::optional<double>(*other.expected_callback_hz_) : std::nullopt),
    sample_count_(other.sample_count_ ? std::optional<int64_t>(*other.sample_count_) : std::nullopt),
    window_us_(other.window_us_ ? std::optional<int64_t>(*other.window_us_) : std::nullopt),
    activity_attached_(other.activity_attached_ ? std::optional<bool>(*other.activity_attached_) : std::nullopt),
    surface_available_(other.surface_available_ ? std::optional<bool>(*other.surface_available_) : std::nullopt),
    touch_boost_enabled_(other.touch_boost_enabled_ ? std::optional<bool>(*other.touch_boost_enabled_) : std::nullopt),
    last_native_request_(other.last_native_request_ ? std::make_unique<RequestResultMessage>(*other.last_native_request_) : nullptr),
    target_generation_(other.target_generation_ ? std::optional<int64_t>(*other.target_generation_) : std::nullopt),
    submission_count_(other.submission_count_ ? std::optional<int64_t>(*other.submission_count_) : std::nullopt) {}

DiagnosticsMessage& DiagnosticsMessage::operator=(const DiagnosticsMessage& other) {
  source_ = other.source_;
  display_id_ = other.display_id_;
  scope_ = other.scope_;
  current_hz_ = other.current_hz_;
  maximum_hz_ = other.maximum_hz_;
  suggested_normal_hz_ = other.suggested_normal_hz_;
  suggested_high_hz_ = other.suggested_high_hz_;
  callback_hz_ = other.callback_hz_;
  expected_callback_hz_ = other.expected_callback_hz_;
  sample_count_ = other.sample_count_;
  window_us_ = other.window_us_;
  activity_attached_ = other.activity_attached_;
  surface_available_ = other.surface_available_;
  touch_boost_enabled_ = other.touch_boost_enabled_;
  last_native_request_ = other.last_native_request_ ? std::make_unique<RequestResultMessage>(*other.last_native_request_) : nullptr;
  target_generation_ = other.target_generation_;
  submission_count_ = other.submission_count_;
  return *this;
}

const std::string* DiagnosticsMessage::source() const {
  return source_ ? &(*source_) : nullptr;
}

void DiagnosticsMessage::set_source(const std::string_view* value_arg) {
  source_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_source(std::string_view value_arg) {
  source_ = value_arg;
}


const std::string* DiagnosticsMessage::display_id() const {
  return display_id_ ? &(*display_id_) : nullptr;
}

void DiagnosticsMessage::set_display_id(const std::string_view* value_arg) {
  display_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_display_id(std::string_view value_arg) {
  display_id_ = value_arg;
}


const std::string* DiagnosticsMessage::scope() const {
  return scope_ ? &(*scope_) : nullptr;
}

void DiagnosticsMessage::set_scope(const std::string_view* value_arg) {
  scope_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_scope(std::string_view value_arg) {
  scope_ = value_arg;
}


const double* DiagnosticsMessage::current_hz() const {
  return current_hz_ ? &(*current_hz_) : nullptr;
}

void DiagnosticsMessage::set_current_hz(const double* value_arg) {
  current_hz_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_current_hz(double value_arg) {
  current_hz_ = value_arg;
}


const double* DiagnosticsMessage::maximum_hz() const {
  return maximum_hz_ ? &(*maximum_hz_) : nullptr;
}

void DiagnosticsMessage::set_maximum_hz(const double* value_arg) {
  maximum_hz_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_maximum_hz(double value_arg) {
  maximum_hz_ = value_arg;
}


const double* DiagnosticsMessage::suggested_normal_hz() const {
  return suggested_normal_hz_ ? &(*suggested_normal_hz_) : nullptr;
}

void DiagnosticsMessage::set_suggested_normal_hz(const double* value_arg) {
  suggested_normal_hz_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_suggested_normal_hz(double value_arg) {
  suggested_normal_hz_ = value_arg;
}


const double* DiagnosticsMessage::suggested_high_hz() const {
  return suggested_high_hz_ ? &(*suggested_high_hz_) : nullptr;
}

void DiagnosticsMessage::set_suggested_high_hz(const double* value_arg) {
  suggested_high_hz_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_suggested_high_hz(double value_arg) {
  suggested_high_hz_ = value_arg;
}


const double* DiagnosticsMessage::callback_hz() const {
  return callback_hz_ ? &(*callback_hz_) : nullptr;
}

void DiagnosticsMessage::set_callback_hz(const double* value_arg) {
  callback_hz_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_callback_hz(double value_arg) {
  callback_hz_ = value_arg;
}


const double* DiagnosticsMessage::expected_callback_hz() const {
  return expected_callback_hz_ ? &(*expected_callback_hz_) : nullptr;
}

void DiagnosticsMessage::set_expected_callback_hz(const double* value_arg) {
  expected_callback_hz_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_expected_callback_hz(double value_arg) {
  expected_callback_hz_ = value_arg;
}


const int64_t* DiagnosticsMessage::sample_count() const {
  return sample_count_ ? &(*sample_count_) : nullptr;
}

void DiagnosticsMessage::set_sample_count(const int64_t* value_arg) {
  sample_count_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_sample_count(int64_t value_arg) {
  sample_count_ = value_arg;
}


const int64_t* DiagnosticsMessage::window_us() const {
  return window_us_ ? &(*window_us_) : nullptr;
}

void DiagnosticsMessage::set_window_us(const int64_t* value_arg) {
  window_us_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_window_us(int64_t value_arg) {
  window_us_ = value_arg;
}


const bool* DiagnosticsMessage::activity_attached() const {
  return activity_attached_ ? &(*activity_attached_) : nullptr;
}

void DiagnosticsMessage::set_activity_attached(const bool* value_arg) {
  activity_attached_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_activity_attached(bool value_arg) {
  activity_attached_ = value_arg;
}


const bool* DiagnosticsMessage::surface_available() const {
  return surface_available_ ? &(*surface_available_) : nullptr;
}

void DiagnosticsMessage::set_surface_available(const bool* value_arg) {
  surface_available_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_surface_available(bool value_arg) {
  surface_available_ = value_arg;
}


const bool* DiagnosticsMessage::touch_boost_enabled() const {
  return touch_boost_enabled_ ? &(*touch_boost_enabled_) : nullptr;
}

void DiagnosticsMessage::set_touch_boost_enabled(const bool* value_arg) {
  touch_boost_enabled_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_touch_boost_enabled(bool value_arg) {
  touch_boost_enabled_ = value_arg;
}


const RequestResultMessage* DiagnosticsMessage::last_native_request() const {
  return last_native_request_.get();
}

void DiagnosticsMessage::set_last_native_request(const RequestResultMessage* value_arg) {
  last_native_request_ = value_arg ? std::make_unique<RequestResultMessage>(*value_arg) : nullptr;
}

void DiagnosticsMessage::set_last_native_request(const RequestResultMessage& value_arg) {
  last_native_request_ = std::make_unique<RequestResultMessage>(value_arg);
}


const int64_t* DiagnosticsMessage::target_generation() const {
  return target_generation_ ? &(*target_generation_) : nullptr;
}

void DiagnosticsMessage::set_target_generation(const int64_t* value_arg) {
  target_generation_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_target_generation(int64_t value_arg) {
  target_generation_ = value_arg;
}


const int64_t* DiagnosticsMessage::submission_count() const {
  return submission_count_ ? &(*submission_count_) : nullptr;
}

void DiagnosticsMessage::set_submission_count(const int64_t* value_arg) {
  submission_count_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DiagnosticsMessage::set_submission_count(int64_t value_arg) {
  submission_count_ = value_arg;
}


EncodableList DiagnosticsMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(17);
  list.push_back(source_ ? EncodableValue(*source_) : EncodableValue());
  list.push_back(display_id_ ? EncodableValue(*display_id_) : EncodableValue());
  list.push_back(scope_ ? EncodableValue(*scope_) : EncodableValue());
  list.push_back(current_hz_ ? EncodableValue(*current_hz_) : EncodableValue());
  list.push_back(maximum_hz_ ? EncodableValue(*maximum_hz_) : EncodableValue());
  list.push_back(suggested_normal_hz_ ? EncodableValue(*suggested_normal_hz_) : EncodableValue());
  list.push_back(suggested_high_hz_ ? EncodableValue(*suggested_high_hz_) : EncodableValue());
  list.push_back(callback_hz_ ? EncodableValue(*callback_hz_) : EncodableValue());
  list.push_back(expected_callback_hz_ ? EncodableValue(*expected_callback_hz_) : EncodableValue());
  list.push_back(sample_count_ ? EncodableValue(*sample_count_) : EncodableValue());
  list.push_back(window_us_ ? EncodableValue(*window_us_) : EncodableValue());
  list.push_back(activity_attached_ ? EncodableValue(*activity_attached_) : EncodableValue());
  list.push_back(surface_available_ ? EncodableValue(*surface_available_) : EncodableValue());
  list.push_back(touch_boost_enabled_ ? EncodableValue(*touch_boost_enabled_) : EncodableValue());
  list.push_back(last_native_request_ ? CustomEncodableValue(*last_native_request_) : EncodableValue());
  list.push_back(target_generation_ ? EncodableValue(*target_generation_) : EncodableValue());
  list.push_back(submission_count_ ? EncodableValue(*submission_count_) : EncodableValue());
  return list;
}

DiagnosticsMessage DiagnosticsMessage::FromEncodableList(const EncodableList& list) {
  DiagnosticsMessage decoded;
  auto& encodable_source = list[0];
  if (!encodable_source.IsNull()) {
    decoded.set_source(std::get<std::string>(encodable_source));
  }
  auto& encodable_display_id = list[1];
  if (!encodable_display_id.IsNull()) {
    decoded.set_display_id(std::get<std::string>(encodable_display_id));
  }
  auto& encodable_scope = list[2];
  if (!encodable_scope.IsNull()) {
    decoded.set_scope(std::get<std::string>(encodable_scope));
  }
  auto& encodable_current_hz = list[3];
  if (!encodable_current_hz.IsNull()) {
    decoded.set_current_hz(std::get<double>(encodable_current_hz));
  }
  auto& encodable_maximum_hz = list[4];
  if (!encodable_maximum_hz.IsNull()) {
    decoded.set_maximum_hz(std::get<double>(encodable_maximum_hz));
  }
  auto& encodable_suggested_normal_hz = list[5];
  if (!encodable_suggested_normal_hz.IsNull()) {
    decoded.set_suggested_normal_hz(std::get<double>(encodable_suggested_normal_hz));
  }
  auto& encodable_suggested_high_hz = list[6];
  if (!encodable_suggested_high_hz.IsNull()) {
    decoded.set_suggested_high_hz(std::get<double>(encodable_suggested_high_hz));
  }
  auto& encodable_callback_hz = list[7];
  if (!encodable_callback_hz.IsNull()) {
    decoded.set_callback_hz(std::get<double>(encodable_callback_hz));
  }
  auto& encodable_expected_callback_hz = list[8];
  if (!encodable_expected_callback_hz.IsNull()) {
    decoded.set_expected_callback_hz(std::get<double>(encodable_expected_callback_hz));
  }
  auto& encodable_sample_count = list[9];
  if (!encodable_sample_count.IsNull()) {
    decoded.set_sample_count(std::get<int64_t>(encodable_sample_count));
  }
  auto& encodable_window_us = list[10];
  if (!encodable_window_us.IsNull()) {
    decoded.set_window_us(std::get<int64_t>(encodable_window_us));
  }
  auto& encodable_activity_attached = list[11];
  if (!encodable_activity_attached.IsNull()) {
    decoded.set_activity_attached(std::get<bool>(encodable_activity_attached));
  }
  auto& encodable_surface_available = list[12];
  if (!encodable_surface_available.IsNull()) {
    decoded.set_surface_available(std::get<bool>(encodable_surface_available));
  }
  auto& encodable_touch_boost_enabled = list[13];
  if (!encodable_touch_boost_enabled.IsNull()) {
    decoded.set_touch_boost_enabled(std::get<bool>(encodable_touch_boost_enabled));
  }
  auto& encodable_last_native_request = list[14];
  if (!encodable_last_native_request.IsNull()) {
    decoded.set_last_native_request(std::any_cast<const RequestResultMessage&>(std::get<CustomEncodableValue>(encodable_last_native_request)));
  }
  auto& encodable_target_generation = list[15];
  if (!encodable_target_generation.IsNull()) {
    decoded.set_target_generation(std::get<int64_t>(encodable_target_generation));
  }
  auto& encodable_submission_count = list[16];
  if (!encodable_submission_count.IsNull()) {
    decoded.set_submission_count(std::get<int64_t>(encodable_submission_count));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<NativePreferenceKind>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<NativeSwitchStrategy>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<NativeRequestStatus>(enum_arg_value));
      }
    case 132: {
        return CustomEncodableValue(DisplayInfoMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(PreferenceMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(RequestResultMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(CapabilitiesMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(DiagnosticsMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(NativePreferenceKind)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<NativePreferenceKind>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(NativeSwitchStrategy)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<NativeSwitchStrategy>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(NativeRequestStatus)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<NativeRequestStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(DisplayInfoMessage)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<DisplayInfoMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PreferenceMessage)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<PreferenceMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RequestResultMessage)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<RequestResultMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(CapabilitiesMessage)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<CapabilitiesMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiagnosticsMessage)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<DiagnosticsMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by RefreshRateHostApi.
const flutter::StandardMessageCodec& RefreshRateHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `RefreshRateHostApi` to handle messages through the `binary_messenger`.
void RefreshRateHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  RefreshRateHostApi* api) {
  RefreshRateHostApi::SetUp(binary_messenger, api, "");
}

void RefreshRateHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  RefreshRateHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.getDisplayInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DisplayInfoMessage> output = api->GetDisplayInfo();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.getCapabilities" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<CapabilitiesMessage> output = api->GetCapabilities();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.getDiagnostics" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DiagnosticsMessage> output = api->GetDiagnostics();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.submitPreference" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_preference_arg = args.at(0);
          if (encodable_preference_arg.IsNull()) {
            reply(WrapError("preference_arg unexpectedly null."));
            return;
          }
          const auto& preference_arg = std::any_cast<const PreferenceMessage&>(std::get<CustomEncodableValue>(encodable_preference_arg));
          ErrorOr<RequestResultMessage> output = api->SubmitPreference(preference_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.resetTouchBoost" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<RequestResultMessage> output = api->ResetTouchBoost();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.startObservation" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->StartObservation();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.stopObservation" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->StopObservation();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.enable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Enable();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.disable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Disable();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.preferMax" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->PreferMax();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.preferDefault" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->PreferDefault();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.matchContent" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_fps_arg = args.at(0);
          if (encodable_fps_arg.IsNull()) {
            reply(WrapError("fps_arg unexpectedly null."));
            return;
          }
          const auto& fps_arg = std::get<double>(encodable_fps_arg);
          std::optional<FlutterError> output = api->MatchContent(fps_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.boost" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_duration_ms_arg = args.at(0);
          if (encodable_duration_ms_arg.IsNull()) {
            reply(WrapError("duration_ms_arg unexpectedly null."));
            return;
          }
          const int64_t duration_ms_arg = encodable_duration_ms_arg.LongValue();
          std::optional<FlutterError> output = api->Boost(duration_ms_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.setCategory" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_category_index_arg = args.at(0);
          if (encodable_category_index_arg.IsNull()) {
            reply(WrapError("category_index_arg unexpectedly null."));
            return;
          }
          const int64_t category_index_arg = encodable_category_index_arg.LongValue();
          std::optional<FlutterError> output = api->SetCategory(category_index_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.setTouchBoost" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_enabled_arg = args.at(0);
          if (encodable_enabled_arg.IsNull()) {
            reply(WrapError("enabled_arg unexpectedly null."));
            return;
          }
          const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
          std::optional<FlutterError> output = api->SetTouchBoost(enabled_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.isSupported" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->IsSupported();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue RefreshRateHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue RefreshRateHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
RefreshRateFlutterApi::RefreshRateFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

RefreshRateFlutterApi::RefreshRateFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& RefreshRateFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void RefreshRateFlutterApi::OnDisplayInfoChanged(
  const DisplayInfoMessage& info_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.refresh_rate.RefreshRateFlutterApi.onDisplayInfoChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(info_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }
  });
}

}  // namespace refresh_rate
