// Copyright 2026 A Few Good Coders (www.afewgoodcoders.com). All rights reserved.
// Use of this source code is governed by a BSD-style license.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_REFRESH_RATE_API_G_H_
#define PIGEON_REFRESH_RATE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace refresh_rate {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class NativePreferenceKind {
  kSystem = 0,
  kHigh = 1,
  kCategory = 2,
  kContent = 3,
  kAtLeast = 4
};

enum class NativeSwitchStrategy {
  kSeamlessOnly = 0,
  kAllowNonSeamless = 1
};

enum class NativeRequestStatus {
  kSubmitted = 0,
  kUnsupported = 1,
  kUnavailable = 2,
  kFailed = 3,
  kSuperseded = 4
};


// Generated class from Pigeon that represents data sent in messages.
class DisplayInfoMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  DisplayInfoMessage();

  // Constructs an object setting all fields.
  explicit DisplayInfoMessage(
    const double* current_rate,
    const double* max_rate,
    const double* min_rate,
    const flutter::EncodableList* supported_rates,
    const bool* is_variable_refresh_rate,
    const double* engine_target_rate,
    const bool* ios_pro_motion_enabled,
    const int64_t* android_api_level,
    const bool* is_low_power_mode,
    const int64_t* thermal_state_index,
    const bool* has_adaptive_refresh_rate,
    const std::string* display_server,
    const int64_t* monitor_count);

  const double* current_rate() const;
  void set_current_rate(const double* value_arg);
  void set_current_rate(double value_arg);

  const double* max_rate() const;
  void set_max_rate(const double* value_arg);
  void set_max_rate(double value_arg);

  const double* min_rate() const;
  void set_min_rate(const double* value_arg);
  void set_min_rate(double value_arg);

  const flutter::EncodableList* supported_rates() const;
  void set_supported_rates(const flutter::EncodableList* value_arg);
  void set_supported_rates(const flutter::EncodableList& value_arg);

  const bool* is_variable_refresh_rate() const;
  void set_is_variable_refresh_rate(const bool* value_arg);
  void set_is_variable_refresh_rate(bool value_arg);

  const double* engine_target_rate() const;
  void set_engine_target_rate(const double* value_arg);
  void set_engine_target_rate(double value_arg);

  const bool* ios_pro_motion_enabled() const;
  void set_ios_pro_motion_enabled(const bool* value_arg);
  void set_ios_pro_motion_enabled(bool value_arg);

  const int64_t* android_api_level() const;
  void set_android_api_level(const int64_t* value_arg);
  void set_android_api_level(int64_t value_arg);

  const bool* is_low_power_mode() const;
  void set_is_low_power_mode(const bool* value_arg);
  void set_is_low_power_mode(bool value_arg);

  const int64_t* thermal_state_index() const;
  void set_thermal_state_index(const int64_t* value_arg);
  void set_thermal_state_index(int64_t value_arg);

  const bool* has_adaptive_refresh_rate() const;
  void set_has_adaptive_refresh_rate(const bool* value_arg);
  void set_has_adaptive_refresh_rate(bool value_arg);

  const std::string* display_server() const;
  void set_display_server(const std::string_view* value_arg);
  void set_display_server(std::string_view value_arg);

  const int64_t* monitor_count() const;
  void set_monitor_count(const int64_t* value_arg);
  void set_monitor_count(int64_t value_arg);


 private:
  static DisplayInfoMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<double> current_rate_;
  std::optional<double> max_rate_;
  std::optional<double> min_rate_;
  std::optional<flutter::EncodableList> supported_rates_;
  std::optional<bool> is_variable_refresh_rate_;
  std::optional<double> engine_target_rate_;
  std::optional<bool> ios_pro_motion_enabled_;
  std::optional<int64_t> android_api_level_;
  std::optional<bool> is_low_power_mode_;
  std::optional<int64_t> thermal_state_index_;
  std::optional<bool> has_adaptive_refresh_rate_;
  std::optional<std::string> display_server_;
  std::optional<int64_t> monitor_count_;

};


// Generated class from Pigeon that represents data sent in messages.
class PreferenceMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  PreferenceMessage();

  // Constructs an object setting all fields.
  explicit PreferenceMessage(
    const NativePreferenceKind* kind,
    const double* fps,
    const int64_t* category,
    const NativeSwitchStrategy* strategy);

  const NativePreferenceKind* kind() const;
  void set_kind(const NativePreferenceKind* value_arg);
  void set_kind(const NativePreferenceKind& value_arg);

  const double* fps() const;
  void set_fps(const double* value_arg);
  void set_fps(double value_arg);

  const int64_t* category() const;
  void set_category(const int64_t* value_arg);
  void set_category(int64_t value_arg);

  const NativeSwitchStrategy* strategy() const;
  void set_strategy(const NativeSwitchStrategy* value_arg);
  void set_strategy(const NativeSwitchStrategy& value_arg);


 private:
  static PreferenceMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class RequestResultMessage;
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<NativePreferenceKind> kind_;
  std::optional<double> fps_;
  std::optional<int64_t> category_;
  std::optional<NativeSwitchStrategy> strategy_;

};


// Generated class from Pigeon that represents data sent in messages.
class RequestResultMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  RequestResultMessage();

  // Constructs an object setting all fields.
  explicit RequestResultMessage(
    const NativeRequestStatus* status,
    const std::string* backend,
    const std::string* scope,
    const std::string* message,
    const PreferenceMessage* preference,
    const int64_t* observed_at_ms);

  ~RequestResultMessage() = default;
  RequestResultMessage(const RequestResultMessage& other);
  RequestResultMessage& operator=(const RequestResultMessage& other);
  RequestResultMessage(RequestResultMessage&& other) = default;
  RequestResultMessage& operator=(RequestResultMessage&& other) noexcept = default;
  const NativeRequestStatus* status() const;
  void set_status(const NativeRequestStatus* value_arg);
  void set_status(const NativeRequestStatus& value_arg);

  const std::string* backend() const;
  void set_backend(const std::string_view* value_arg);
  void set_backend(std::string_view value_arg);

  const std::string* scope() const;
  void set_scope(const std::string_view* value_arg);
  void set_scope(std::string_view value_arg);

  const std::string* message() const;
  void set_message(const std::string_view* value_arg);
  void set_message(std::string_view value_arg);

  const PreferenceMessage* preference() const;
  void set_preference(const PreferenceMessage* value_arg);
  void set_preference(const PreferenceMessage& value_arg);

  const int64_t* observed_at_ms() const;
  void set_observed_at_ms(const int64_t* value_arg);
  void set_observed_at_ms(int64_t value_arg);


 private:
  static RequestResultMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiagnosticsMessage;
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<NativeRequestStatus> status_;
  std::optional<std::string> backend_;
  std::optional<std::string> scope_;
  std::optional<std::string> message_;
  std::unique_ptr<PreferenceMessage> preference_;
  std::optional<int64_t> observed_at_ms_;

};


// Generated class from Pigeon that represents data sent in messages.
class CapabilitiesMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  CapabilitiesMessage();

  // Constructs an object setting all fields.
  explicit CapabilitiesMessage(
    const bool* query,
    const bool* surface_voting,
    const bool* window_preferences,
    const bool* category_hints,
    const bool* engine_control,
    const bool* presentation_observation,
    const bool* at_least,
    const bool* content_matching,
    const bool* touch_boost,
    const bool* callback_observation);

  const bool* query() const;
  void set_query(const bool* value_arg);
  void set_query(bool value_arg);

  const bool* surface_voting() const;
  void set_surface_voting(const bool* value_arg);
  void set_surface_voting(bool value_arg);

  const bool* window_preferences() const;
  void set_window_preferences(const bool* value_arg);
  void set_window_preferences(bool value_arg);

  const bool* category_hints() const;
  void set_category_hints(const bool* value_arg);
  void set_category_hints(bool value_arg);

  const bool* engine_control() const;
  void set_engine_control(const bool* value_arg);
  void set_engine_control(bool value_arg);

  const bool* presentation_observation() const;
  void set_presentation_observation(const bool* value_arg);
  void set_presentation_observation(bool value_arg);

  const bool* at_least() const;
  void set_at_least(const bool* value_arg);
  void set_at_least(bool value_arg);

  const bool* content_matching() const;
  void set_content_matching(const bool* value_arg);
  void set_content_matching(bool value_arg);

  const bool* touch_boost() const;
  void set_touch_boost(const bool* value_arg);
  void set_touch_boost(bool value_arg);

  const bool* callback_observation() const;
  void set_callback_observation(const bool* value_arg);
  void set_callback_observation(bool value_arg);


 private:
  static CapabilitiesMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> query_;
  std::optional<bool> surface_voting_;
  std::optional<bool> window_preferences_;
  std::optional<bool> category_hints_;
  std::optional<bool> engine_control_;
  std::optional<bool> presentation_observation_;
  std::optional<bool> at_least_;
  std::optional<bool> content_matching_;
  std::optional<bool> touch_boost_;
  std::optional<bool> callback_observation_;

};


// Generated class from Pigeon that represents data sent in messages.
class DiagnosticsMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  DiagnosticsMessage();

  // Constructs an object setting all fields.
  explicit DiagnosticsMessage(
    const std::string* source,
    const std::string* display_id,
    const std::string* scope,
    const double* current_hz,
    const double* maximum_hz,
    const double* suggested_normal_hz,
    const double* suggested_high_hz,
    const double* callback_hz,
    const double* expected_callback_hz,
    const int64_t* sample_count,
    const int64_t* window_us,
    const bool* activity_attached,
    const bool* surface_available,
    const bool* touch_boost_enabled,
    const RequestResultMessage* last_native_request,
    const int64_t* target_generation,
    const int64_t* submission_count);

  ~DiagnosticsMessage() = default;
  DiagnosticsMessage(const DiagnosticsMessage& other);
  DiagnosticsMessage& operator=(const DiagnosticsMessage& other);
  DiagnosticsMessage(DiagnosticsMessage&& other) = default;
  DiagnosticsMessage& operator=(DiagnosticsMessage&& other) noexcept = default;
  const std::string* source() const;
  void set_source(const std::string_view* value_arg);
  void set_source(std::string_view value_arg);

  const std::string* display_id() const;
  void set_display_id(const std::string_view* value_arg);
  void set_display_id(std::string_view value_arg);

  const std::string* scope() const;
  void set_scope(const std::string_view* value_arg);
  void set_scope(std::string_view value_arg);

  const double* current_hz() const;
  void set_current_hz(const double* value_arg);
  void set_current_hz(double value_arg);

  const double* maximum_hz() const;
  void set_maximum_hz(const double* value_arg);
  void set_maximum_hz(double value_arg);

  const double* suggested_normal_hz() const;
  void set_suggested_normal_hz(const double* value_arg);
  void set_suggested_normal_hz(double value_arg);

  const double* suggested_high_hz() const;
  void set_suggested_high_hz(const double* value_arg);
  void set_suggested_high_hz(double value_arg);

  const double* callback_hz() const;
  void set_callback_hz(const double* value_arg);
  void set_callback_hz(double value_arg);

  const double* expected_callback_hz() const;
  void set_expected_callback_hz(const double* value_arg);
  void set_expected_callback_hz(double value_arg);

  const int64_t* sample_count() const;
  void set_sample_count(const int64_t* value_arg);
  void set_sample_count(int64_t value_arg);

  const int64_t* window_us() const;
  void set_window_us(const int64_t* value_arg);
  void set_window_us(int64_t value_arg);

  const bool* activity_attached() const;
  void set_activity_attached(const bool* value_arg);
  void set_activity_attached(bool value_arg);

  const bool* surface_available() const;
  void set_surface_available(const bool* value_arg);
  void set_surface_available(bool value_arg);

  const bool* touch_boost_enabled() const;
  void set_touch_boost_enabled(const bool* value_arg);
  void set_touch_boost_enabled(bool value_arg);

  const RequestResultMessage* last_native_request() const;
  void set_last_native_request(const RequestResultMessage* value_arg);
  void set_last_native_request(const RequestResultMessage& value_arg);

  const int64_t* target_generation() const;
  void set_target_generation(const int64_t* value_arg);
  void set_target_generation(int64_t value_arg);

  const int64_t* submission_count() const;
  void set_submission_count(const int64_t* value_arg);
  void set_submission_count(int64_t value_arg);


 private:
  static DiagnosticsMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> source_;
  std::optional<std::string> display_id_;
  std::optional<std::string> scope_;
  std::optional<double> current_hz_;
  std::optional<double> maximum_hz_;
  std::optional<double> suggested_normal_hz_;
  std::optional<double> suggested_high_hz_;
  std::optional<double> callback_hz_;
  std::optional<double> expected_callback_hz_;
  std::optional<int64_t> sample_count_;
  std::optional<int64_t> window_us_;
  std::optional<bool> activity_attached_;
  std::optional<bool> surface_available_;
  std::optional<bool> touch_boost_enabled_;
  std::unique_ptr<RequestResultMessage> last_native_request_;
  std::optional<int64_t> target_generation_;
  std::optional<int64_t> submission_count_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class RefreshRateHostApi {
 public:
  RefreshRateHostApi(const RefreshRateHostApi&) = delete;
  RefreshRateHostApi& operator=(const RefreshRateHostApi&) = delete;
  virtual ~RefreshRateHostApi() {}
  virtual ErrorOr<DisplayInfoMessage> GetDisplayInfo() = 0;
  virtual ErrorOr<CapabilitiesMessage> GetCapabilities() = 0;
  virtual ErrorOr<DiagnosticsMessage> GetDiagnostics() = 0;
  virtual ErrorOr<RequestResultMessage> SubmitPreference(const PreferenceMessage& preference) = 0;
  virtual ErrorOr<RequestResultMessage> ResetTouchBoost() = 0;
  virtual ErrorOr<bool> StartObservation() = 0;
  virtual std::optional<FlutterError> StopObservation() = 0;
  virtual std::optional<FlutterError> Enable() = 0;
  virtual std::optional<FlutterError> Disable() = 0;
  virtual std::optional<FlutterError> PreferMax() = 0;
  virtual std::optional<FlutterError> PreferDefault() = 0;
  virtual std::optional<FlutterError> MatchContent(double fps) = 0;
  virtual std::optional<FlutterError> Boost(int64_t duration_ms) = 0;
  virtual std::optional<FlutterError> SetCategory(int64_t category_index) = 0;
  virtual std::optional<FlutterError> SetTouchBoost(bool enabled) = 0;
  virtual ErrorOr<bool> IsSupported() = 0;

  // The codec used by RefreshRateHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `RefreshRateHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    RefreshRateHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    RefreshRateHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  RefreshRateHostApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class RefreshRateFlutterApi {
 public:
  RefreshRateFlutterApi(flutter::BinaryMessenger* binary_messenger);
  RefreshRateFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnDisplayInfoChanged(
    const DisplayInfoMessage& info,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace refresh_rate
#endif  // PIGEON_REFRESH_RATE_API_G_H_
